### ISSUE TITLE
Metrics Collector Module Fails with Invalid logs uploaded request schema

### ISSUE THREAD

**Issue by evmoreno** [veyalla/ehm#2]
Unhandled Exception: System.AggregateException: One or more errors occurred. (Invalid logs upload request schema version ) ---> System.InvalidOperationException: Invalid logs upload request schema version
   at MetricsCollector.SchemaVersionHelper.CompareMajorVersion(Version expectedVersion, String actualVersionString, String context) in /app/SchemaVersionHelper.cs:line 11
   at MetricsCollector.Program.GetConfiguration(ModuleClient ioTHubModuleClient) in /app/Program.cs:line 105
   at MetricsCollector.Program.Init() in /app/Program.cs:line 52
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MetricsCollector.Program.Main(String[] args) in /app/Program.cs:line 22

Create Container Options set :

{
  "properties.desired": {
    "schemaVersion": "1.0",
    "scrapeFrequencySecs": 300,
    "metricsFormat": "Json",
    "syncTarget": "AzureLogAnalytics",
    "endpoints": {
      "edgeHub": "http://edgeHub:9600/metrics"
    }
  }
}

Any advise?

**Comment by evmoreno** [comment]
Updated Desired Properties - User Error

{
    "schemaVersion": "1.0",
    "scrapeFrequencySecs": 300,
    "metricsFormat": "Json",
    "syncTarget": "AzureLogAnalytics",
    "endpoints": {
        "edgeHub": "http://edgeHub:9600/metrics"
    }
}
