### ISSUE TITLE
Metrics collector fails when sending data on windows

### ISSUE THREAD

**Issue by ChristianEder** [veyalla/ehm#4]
In order to evaluate the use of Edge Hub Metrics  for our project, I tried to set up IoT Edge devices on VMs for Linux (with Linux Containers) and Windows (with Windows Containers). While the Linux version worked just fine, I keep having problems with the windows version. My setup is:

- A Windows 10 Hyper-V VM 
- Azure IoT Edge Release 1.0.9 installed with Windows Containers
- Edge Agent and Edge Hub modules using tag 1.0.9-rc6
- ExperimentalFeatures__Enabled and ExperimentalFeatures__EnableMetrics set to true
- EdgeHub using these create options

`{
  "HostConfig": {
    "PortBindings": {
      "443/tcp": [
        {
          "HostPort": "443"
        }
      ],
      "5671/tcp": [
        {
          "HostPort": "5671"
        }
      ],
      "8883/tcp": [
        {
          "HostPort": "8883"
        }
      ]
    }
  },
  "User": "ContainerAdministrator",
  "ExposedPorts": {
    "9600/tcp": {},
    "5671/tcp": {},
    "8883/tcp": {}
  }
}`

- The MetricsCollector module installed using tag 0.0.5-windows-amd64 and with this twin:

`{
    "schemaVersion": "1.0",
    "scrapeFrequencySecs": 10,
    "metricsFormat": "Json",
    "syncTarget": "IoTHub",
    "endpoints": {
        "edgeAgent": "http://edgeAgent:9600/metrics",
        "edgeHub": "http://edgeHub:9600/metrics"
    }
}`

While the collector seems to be able to retrieve the metrics from the edgeAgent and edgeHub, it fails to send them to IoT Hub. I tried around if it might be some connectivity issue from my VM, but for example the simulated temperature sensor module succeeds to send telemetry to IoT Hub. The error message that I get is:

> Scraping endpoint http://edgeAgent:9600/metrics
Got metrics from endpoint [http://edgeAgent:9600/metrics, http://172.23.15.202:9600/metrics]
Scraping endpoint http://edgeHub:9600/metrics
Got metrics from endpoint [http://edgeHub:9600/metrics, http://172.23.13.128:9600/metrics]
Error scraping and syncing metrics - System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.Azure.Amqp.AmqpMessage.get_DataBody()
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSendingLink.SendMessagesAsync(IEnumerable`1 messages, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.SendMessagesAsync(IEnumerable`1 messages, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.SendEventsAsync(IEnumerable`1 messages, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendEventAsync(IEnumerable`1 messages, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(IEnumerable`1 messages, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventBatchAsync(IEnumerable`1 messages)
   at MetricsCollector.IoTHubMetricsSync.ScrapeAndSync() in C:\app\IoTHubMetricsSync.cs:line 30

Any ideas? I know that the metrics collector is no officially supported module - we didnt plan to use it in production, just for evaluating the edge hub metrics features for our project.

**Comment by veyalla** [comment]
Thanks for the report, I plan to update the sample with 1.0.10-rc1 and new sample collector in a couple of weeks. This should be resolved with that update.

**Comment by veyalla** [comment]
Sample has been migrated to: https://labs.iotedge.dev/codelabs/monitor-iotedge

This should be fixed there.
